version: "3.8"

services:
  app:
    build: ./docker/php
    container_name: ujicoba_app
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: ujicoba_nginx
    ports:
      - "8092:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: ujicoba_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catatanharian
    volumes:
      # Jalankan skrip init.sql saat database pertama kali dibuat
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ujicoba_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
